"""
Column allowlists for each Supabase target table.

Only columns present in both the DataFrame AND the allowlist are upserted,
so adding new API fields never accidentally breaks the schema.
"""

D_I_PRODUCTS_COLS: set[str] = {
    "productId", "autoAssemble", "categoryId", "description", "expiryNotificationDays",
    "height", "hsTariffNumber", "includeQuantityBuildable", "isActive", "isManufacturable",
    "itemType", "lastModifiedById", "lastModifiedDateTime", "lastVendorId", "length",
    "originCountry", "purchasingUom", "remarks", "salesUom", "shelfLifeDays", "sku",
    "standardUomName", "timestamp", "trackExpiry", "trackLots", "trackSerials",
    "weight", "width", "New_Product_name",
    "Custom_Field_1", "Custom_Field_2", "Custom_Field_3", "Custom_Field_4",
    "Custom_Field_5", "Custom_Field_6", "Custom_Field_7", "Custom_Field_8",
    "Custom_Field_9", "Custom_Field_10",
    "last_refresh", "id", "locationId", "imageSmallUrl",
    "quantityOnHand", "quantityOnOrder", "quantityOnPurchaseOrder", "quantityOnWorkOrder",
    "quantityOnTransferOrder", "quantityReserved", "quantityReservedForSales",
    "quantityReservedForManufacturing", "quantityReservedForTransfers",
    "quantityReservedForBuilds", "quantityAvailable", "rawQuantityAvailable",
    "quantityPicked", "quantityInTransit", "quantityBuildable",
    "cost_value", "productCostId", "name", "unitOfMeasure", "price", "cost",
    "barcode", "quantityAnticipated", "quantityCommitted", "lastModifiedDttm",
}

D_I_PRODUCT_LOC_INV_COLS: set[str] = {
    "id", "productId", "locationId", "location_name", "imageSmallUrl",
    "quantityOnHand", "quantityOnOrder", "quantityOnPurchaseOrder", "quantityOnWorkOrder",
    "quantityOnTransferOrder", "quantityReserved", "quantityReservedForSales",
    "quantityReservedForManufacturing", "quantityReservedForTransfers",
    "quantityReservedForBuilds", "quantityAvailable", "rawQuantityAvailable",
    "quantityPicked", "quantityInTransit", "quantityBuildable", "quantityAnticipated",
    "last_refresh",
}

F_I_PURCHASE_ORDERS_COLS: set[str] = {
    "line_id", "purchaseOrderId", "product_id", "product_name", "product_sku",
    "quantity_ordered", "quantity_received", "quantity_returned", "unit_price",
    "line_total", "sublocation", "location_name", "itemType", "item_type",
    "amountPaid", "balance", "calculateTax2OnTax1", "carrier", "contactName",
    "currencyId", "dueDate", "email", "exchangeRate", "exchangeRateAutoPulled",
    "freight", "inventoryStatus", "isCancelled", "isCompleted", "isQuote",
    "isTaxInclusive", "lastModifiedById", "locationId", "orderDate", "orderNumber",
    "orderRemarks", "paidDate", "paymentStatus", "phone", "receiveRemarks",
    "returnExtra", "returnFee", "returnRemarks", "shipToCompanyName", "showShipping",
    "subTotal", "tax1", "tax1Name", "tax1OnShipping", "tax1Rate",
    "tax2", "tax2Name", "tax2OnShipping", "tax2Rate", "taxingSchemeId",
    "timestamp", "total", "unstockRemarks", "vendorId", "vendorOrderNumber",
    "customFields_custom1", "customFields_custom2", "customFields_custom3",
    "customFields_custom4", "customFields_custom5", "customFields_custom6",
    "customFields_custom7", "customFields_custom8", "customFields_custom9",
    "customFields_custom10", "nonVendorCosts_value", "nonVendorCosts_isPercent",
    "shipToAddress_address1", "shipToAddress_address2", "shipToAddress_city",
    "shipToAddress_state", "shipToAddress_country", "shipToAddress_postalCode",
    "shipToAddress_remarks", "vendorAddress_address1", "vendorAddress_address2",
    "vendorAddress_city", "vendorAddress_state", "vendorAddress_country",
    "vendorAddress_postalCode", "last_refresh",
}

F_I_SALES_ORDER_COLS: set[str] = {
    "line_id", "salesOrderId", "salesOrderLineId", "balance", "customerId",
    "isCancelled", "isCompleted", "isQuote", "isTaxInclusive", "orderNumber",
    "orderDate", "subTotal", "tax1Rate", "tax2Rate", "timestamp", "total",
    "inventoryStatus", "exchangeRate", "exchangeRateAutoPulled", "paymentStatus",
    "invoicedDate", "needsConfirmation",
    "description", "isDiscarded", "productId", "returnDate", "serviceCompleted",
    "taxCodeId", "unitPrice", "discount_value", "discount_isPercent",
    "quantity_standardQuantity", "quantity_uomQuantity", "quantity_uom",
    "quantity_serialNumbers",
    "product_productId", "product_autoAssemble", "product_categoryId",
    "product_customFields_custom1", "product_customFields_custom2",
    "product_customFields_custom3", "product_customFields_custom4",
    "product_customFields_custom5", "product_customFields_custom6",
    "product_customFields_custom7", "product_customFields_custom8",
    "product_customFields_custom9", "product_customFields_custom10",
    "product_description", "product_expiryNotificationDays", "product_height",
    "product_hsTariffNumber", "product_includeQuantityBuildable", "product_isActive",
    "product_isManufacturable", "product_itemType", "product_lastModifiedById",
    "product_lastModifiedDateTime", "product_lastVendorId", "product_length",
    "product_name", "product_originCountry", "product_purchasingUom",
    "product_remarks", "product_salesUom", "product_shelfLifeDays", "product_sku",
    "product_standardUomName", "product_timestamp", "product_trackExpiry",
    "product_trackLots", "product_trackSerials", "product_weight", "product_width",
    "product_id", "product_category_name", "product_category_id",
    "product_cost_value", "product_cost_id",
    "cogs_value", "cogs_id", "cogs_salesOrderId", "cogs_salesOrder_id",
    "cogs_salesOrder_orderNumber", "cogs_salesOrder_orderDate",
    "nonCustomerCost_value", "nonCustomerCost_isPercent",
    "customFields_custom1", "customFields_custom2", "customFields_custom3",
    "customFields_custom4", "customFields_custom5", "customFields_custom6",
    "customFields_custom7", "customFields_custom8", "customFields_custom9",
    "customFields_custom10",
    "pricing_scheme_name", "pricing_scheme_id", "pricing_scheme_isActive",
    "pricing_scheme_isDefault", "pricing_scheme_isTaxInclusive", "pricing_scheme_currencyId",
    "pricing_scheme_currency_name", "pricing_scheme_currency_isoCode",
    "pricing_scheme_currency_symbol", "pricing_scheme_currency_decimalPlaces",
    "pricing_scheme_currency_isSymbolFirst", "pricing_scheme_currency_decimalSeparator",
    "pricing_scheme_currency_thousandsSeparator", "pricing_scheme_currency_negativeType",
    "pricing_scheme_currency_exchangeRate", "pricing_scheme_currency_isManual",
    "pricing_scheme_productPrices_count", "pricing_scheme_productPrice_fixedMarkup",
    "pricing_scheme_productPrice_priceType", "pricing_scheme_productPrice_id",
    "pricing_scheme_productPrice_unitPrice", "pricing_scheme_productPrice_pricingSchemeId",
    "pricing_scheme_productPrice_product_name", "pricing_scheme_productPrice_product_sku",
    "pricing_scheme_productPrice_product_autoAssemble", "pricing_scheme_productPrice_product_id",
    "pricing_scheme_productPrice_product_category_name",
    "pricing_scheme_productPrice_product_category_id",
    "pricing_scheme_productPrice_product_category_isDefault",
    "pricing_scheme_productPrice_product_cost_direct",
    "pricing_scheme_productPrice_product_cost_value",
    "pricing_scheme_productPrice_product_cost_id",
    "pricing_scheme_productPrice_product_cost_productId",
    "pricing_scheme_productPrice_product_itemType",
    "salesRep", "salesRepTeamMemberId", "assignedToTeamMemberId",
    "salesRep_name", "salesRep_email", "salesRep_isActive", "salesRep_isInternal",
    "salesRep_canBeSalesRep", "salesRep_accessAllLocations", "salesRep_teamMemberId",
    "salesRep_accessLocationIds", "assignedTo_name", "assignedTo_email",
    "assignedTo_isActive", "assignedTo_isInternal", "assignedTo_canBeSalesRep",
    "assignedTo_accessAllLocations", "assignedTo_teamMemberId", "assignedTo_accessLocationIds",
    "status", "quantity", "lineTotal", "isActive",
    "line_cogs_allocated", "line_product_cost",
    "last_refresh",
}

D_I_LOCATIONS_COLS: set[str] = {
    "locationId", "name", "isActive", "isDefault",
    "address1", "address2", "city", "state", "country", "postalCode",
    "remarks", "addressType", "timestamp", "last_refresh",
}

D_I_CUSTOMERS_COLS: set[str] = {
    "customerId", "customerNumber", "name", "companyName", "contactName",
    "email", "phone", "fax", "website",
    "addressLine1", "addressLine2", "city", "state", "postalCode", "country",
    "isActive", "taxingSchemeId", "pricingSchemeId", "taxExemptNumber",
    "defaultSalesRep", "defaultSalesRepTeamMemberId",
    "defaultBillingAddressId", "defaultShippingAddressId",
    "defaultLocationId", "defaultCarrier",
    "defaultPaymentMethod", "defaultPaymentTermsId",
    "discount", "creditLimit", "notes", "remarks",
    "salesRep_name", "salesRep_email", "salesRep_isActive", "salesRep_isInternal",
    "salesRep_canBeSalesRep", "salesRep_accessAllLocations", "salesRep_teamMemberId",
    "salesRep_accessLocationIds",
    "Custom_Field_1", "Custom_Field_2", "Custom_Field_3", "Custom_Field_4",
    "Custom_Field_5", "Custom_Field_6", "Custom_Field_7", "Custom_Field_8",
    "Custom_Field_9", "Custom_Field_10",
    "Customer Category", "Longitude", "Latitude",
    "timestamp", "lastModifiedById", "lastModifiedDttm",
    "last_refresh",
}
